name: Daily Telegram Signal Bullish/Bearish

on:
  schedule:
    - cron: '0 4 * * 1-5'   # 09:30 IST
    - cron: '30 4 * * 1-5'  # 10:00 IST
    - cron: '0 5 * * 1-5'   # 10:30 IST
    - cron: '30 5 * * 1-5'  # 11:00 IST
    - cron: '0 6 * * 1-5'   # 11:30 IST
    - cron: '30 6 * * 1-5'  # 12:00 IST
    - cron: '0 7 * * 1-5'   # 12:30 IST
    - cron: '30 7 * * 1-5'  # 13:00 IST
    - cron: '0 8 * * 1-5'   # 13:30 IST
    - cron: '30 8 * * 1-5'  # 14:00 IST
    - cron: '0 9 * * 1-5'   # 14:30 IST
    - cron: '30 9 * * 1-5'  # 15:00 IST
  workflow_dispatch:        # Allows manual trigger from GitHub

jobs:
  run-telegram-signal:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance nsetools pandas requests

    - name: Run script
      run: python main.py
